### ISSUE TITLE
Results Question

### ISSUE THREAD

**Issue by lxtGH** [lkeab/BCNet#1]
Hi! Thisi is a very insteresting paper.  I have a question on results comparison.
In tab.3 BCNet + FCOS achieves 39.6 mask ap. Is this 3x training or 1x training on coco?
How about BCNet + Faster R-CNN?

**Comment by lkeab** [comment]
Thanks for the question. For Faster R-CNN, we adopt 3x training. For FCOS, we adopt 2x training.

**Comment by lxtGH** [comment]
Hi! @lkeab  What about R50 Faster-RCNN ? And How about the results of FCOS 3x training?

**Comment by lkeab** [comment]
R50 Faster-RCNN is 3X.  For FCOS 3x training, I need a further check.

**Comment by lxtGH** [comment]
If R50 Faster-RCNN is 3X,what are resuls of other methods? 
In my experience, for detectron2 implementation, mask-rcnn r50 3x can achieves 37.0 while pointrend can achieves 38.2 on COCO test-dev.

**Comment by lkeab** [comment]
Since there are too many methods for comparison, I adopt their result either from their paper comparions or github descriptions. My training on test-dev (following strategies in CenterMask) has multi-scale, but not in test stage.

**Comment by lxtGH** [comment]
OK I got it! Thanks for your reply.
