### ISSUE TITLE
Dataset replacement

### ISSUE THREAD

**Issue by EVXEVXYA** [lkeab/BCNet#100]
If I wanna to use the dataset created by myself, is it right to create the dataset into coco format? What kinds of documents need to be changed? Thanks!

**Comment by lkeab** [comment]
into coco format; you could see our script process.sh [https://github.com/lkeab/BCNet#reference-script-for-producing-bilayer-mask-annotation].

**Comment by wangxueping78** [comment]
> If I wanna to use the dataset created by myself, is it right to create the dataset into coco format? What kinds of documents need to be changed? Thanks!

Use your own data to train this network, have you succeeded?

**Comment by EVXEVXYA** [comment]
> > If I wanna to use the dataset created by myself, is it right to create the dataset into coco format? What kinds of documents need to be changed? Thanks!
> 
> Use your own data to train this network, have you succeeded?

Still working on it.

**Comment by EVXEVXYA** [comment]
Hello again!
I run the program with COCO2017, got the error as below. Please help, thanks!

![报错1  2022-05-10 095346](https://user-images.githubusercontent.com/71375166/167528277-fcac8541-4baa-40c4-8d6e-5347f9070970.jpg)

Configuration as follows:

![配置](https://user-images.githubusercontent.com/71375166/167528581-685f1c70-d0eb-4e03-bc39-3de234733ebd.jpg)

**Comment by wangxueping78** [comment]
#if 'train' in file_name:
        #file_name = file_name.split('train2017/', 1)[1]
 #if 'occ' in file_name:
        #file_name = file_name.split('occ2017/', 1)[1]

you can try to commment  above codes  at lines 47-51 of file  "detection_utils.py".

**Comment by EVXEVXYA** [comment]
Thanks for your advice@wangxueping78 , but it doesn't seem to work, still got the error.

**Comment by trugle** [comment]
> > > If I wanna to use the dataset created by myself, is it right to create the dataset into coco format? What kinds of documents need to be changed? Thanks!
> > 
> > 
> > Use your own data to train this network, have you succeeded?
> 
> Still working on it.

Have you succeeded on your own datasets?
