### ISSUE TITLE
IndexError: list index out of range when training myself datas

### ISSUE THREAD

**Issue by wangxueping78** [lkeab/BCNet#102]
![P9$LW2QQ~5D0%R2@H4 7C$I](https://user-images.githubusercontent.com/43226404/165910251-c922100d-399e-4c4e-ac9f-cc7b3578e70e.png)

**Comment by lkeab** [comment]
which command leads to this error? can you print out the 'file_name' for debugging?

**Comment by wangxueping78** [comment]
CUDA_VISIBLE_DEVICES=0 python3 tools/train_broccoli_net.py --num-gpus 1 --config-file configs/fcos/fcos_imprv_R_50_FPN.yaml 2>&1 | tee log/train_log.txt，train_broccoli_net.py is the file I rewritten to train my own data.

**Comment by wangxueping78** [comment]
> which command leads to this error? can you print out the 'file_name' for debugging?

I have solved the previous problem, now I encounter a new problem：RuntimeError: CUDA error: no kernel image is available for execution on the device.
My gpu is RTX3080Ti, cuda 10.1,pytorch 1.4 ,cudatoolkit 10.1，what is the gpu version used in your experiment?

**Comment by Wyatt823** [comment]
请问这个问题您解决了吗？
