### ISSUE TITLE
train when config file is fcos_imprv_R_101_FPN.yaml

### ISSUE THREAD

**Issue by wangxueping78** [lkeab/BCNet#106]
When I would like train BCNet using the config file"fcos_imprv_R_101_FPN.yaml",I found it seems to be used as the evaluation.Then I modified '_BASE_: "../Base-FCOS-test-2x.yaml" 'in this file to '_BASE_: "../Base-FCOS.yaml" ' ，and it could excult and finsh the training.However, why the evalution effect is not ideal, not as good as R50?

**Comment by lkeab** [comment]
which r50 model are you comparing with? does the compared model have the same training schedule period?

**Comment by wangxueping78** [comment]
R50 refers to  fcos_imprv_R_101_FPN.yaml, and  the training schedule periods  are the same.
