### ISSUE TITLE
train by myself datasets

### ISSUE THREAD

**Issue by wangxueping78** [lkeab/BCNet#108]
I am training the bcnet network with a dataset I made myself and I wrote a script myself to register my dataset successfuly.
 my json tags：（for example）

‘segmentation’ refers to the Occludee,and 'leaf_mask' refers to the Occluder
![image](https://user-images.githubusercontent.com/43226404/167983927-dd4e60c2-e8e5-40e1-ac11-9db21ac8533c.png)

So  I made a little modification for codes according to my json tags :

 in detectron/data/datasets/coco.py
![image](https://user-images.githubusercontent.com/43226404/167984151-47149231-d89a-4ff9-b38b-bd1924c7efba.png)
![image](https://user-images.githubusercontent.com/43226404/167984177-10791f45-6cb1-450a-b1e3-8921c9072fbb.png)

in detectron/data/detection_utils.py
![image](https://user-images.githubusercontent.com/43226404/167984250-520aa7fd-5a9e-4aa4-99a2-3b8d85471e87.png)

I could start  training but I found some exceptions：
![94 LFNV`E9ARA3 JIELQZ 8](https://user-images.githubusercontent.com/43226404/167984408-5a807459-7536-46e0-a8d1-403928ec2c67.png)
'loss_mask_bo' and 'loss_boundary_bo'  are 0.000 always.

can you help me ?

**Comment by wangxueping78** [comment]
And after the training, the visualization results are only the Occludee, not the occluded objects.

**Comment by wangxueping78** [comment]
And after the training, the visualization results are only the Occludee, not the  Occluder.

**Comment by lkeab** [comment]
can you visualize your "segmentation" and "leaf_mask" groundtruth masks?

**Comment by wangxueping78** [comment]
Yes, I have visual steps when I follow the labelme operation and visualize successfuly.
