### ISSUE TITLE
Training with my own data - Input Image size 

### ISSUE THREAD

**Issue by CallMeDek** [lkeab/BCNet#109]
Hi @lkeab 

Thanks for your work. It is expected to be helpful for my work. 
Btw, I have a question for you. According to your paper, input size is (600, 900). 
Is it fixed? So then, I have to prepare my data fitting to it?

Sincerely
Dek

**Comment by lkeab** [comment]
I don't think you need to fit your images to a specific size, like coco has various image sizes. During training, the image sizes will be adjusted by the data loader automatically.
