### ISSUE TITLE
how do i  know if an instance is Occluder or Occludee?

### ISSUE THREAD

**Issue by zzq96** [lkeab/BCNet#11]
Hi.
I have read this paper. 
But I still confuse how to distinguish if an instance is an occluder or occludee when training the network. o(╥﹏╥)o

**Comment by lkeab** [comment]
Thanks for watching our work. During training, for each instance, we first get its bounding box Bi, and then using the GT annotation file to find all neighboring objects with bounding box overlapping with the current instance, and crop/group their mask annotations inside the box Bi. Thus, we treat the object itself as occludee and the other overlapping objects inside Bi as the occluders.  You can also refer to the python file related to process.sh for more details.

**Comment by lkeab** [comment]
During the test time, since our network has bilayer structure, the first image layer will detects the occluders while the second layer will predict the occludee.

**Comment by Jacobew** [comment]
> During the test time, since our network has bilayer structure, the first image layer will detects the occluders while the second layer will predict the occludee.

What if there is no occlusion? Which GCN branch will output the target mask?

**Comment by lkeab** [comment]
The second one, the first will predict empty masks.

**Comment by trungpham2606** [comment]
Dear @lkeab,
I have a question about your algorithm, so as what you have said, lets consider the man and horse image for example:
![image](https://user-images.githubusercontent.com/35657426/124846401-ed21d900-dfc2-11eb-9624-1479d706a6d6.png)
Now we are considering the human instance. It will be set as occludee, and a part of the horse will be set as occluder even the horse doesnt occlude the human ? 
If I understand it correctly, your idea is enhancing the accuracy of instance masks between each objects in a bounding box, isnt it ?

**Comment by lkeab** [comment]
In this situation, regarding to the bbox of the human, yes, it is an approximate.

**Comment by JiajiaLi04** [comment]
Dear @lkeab,
I have a question about your algorithm. Let's take the man and horse  for example  in the above picture.
As you said, regarding to the bbox of the human, part of the horse will be se as occluder.  I am confusing whthere this part of the horse will have bad influence on the final result of the person's segmentation?  Thanks in advance!

**Comment by lkeab** [comment]
COCO test-dev is segmenting the visible part of the objects. The part of the horse that occludes the human will not influence the prediction in these visible regions of the person. The benefit of the bilayer handling is to help separate/distinguish the overlapping parts between objects well.
