### ISSUE TITLE
if the Occluder is not in the category tag

### ISSUE THREAD

**Issue by wangxueping78** [lkeab/BCNet#110]
If the Occluder marked in the json file  is not in the category tags,can it be identified？

**Comment by lkeab** [comment]
During training, if it is class-agnostic for occluder mask prediction, then it should be able to identify.

**Comment by wangxueping78** [comment]
what's the mean of  'it is class-agnostic for occluder mask prediction' ? Can you explain in detail

**Comment by wangxueping78** [comment]
@lkeab  
    The pictures of my dataset are tomatoes that are occluded by leaves to varying degrees. The categories of the dataset are tomatoes and leaves. I have annotated both tomatoes and leaves, but the category id in each of my annotation files is set to tomatoes. The experimental result is that I can visualize the tomatoes but not the leaves.
    Can you help me ?

**Comment by lkeab** [comment]
can you set the training into class-agnostic? That means the mask head will only predict the target object mask with single channel dimension instead of C (class number) dimensions.

**Comment by wangxueping78** [comment]
How to set the training into class-agnostic ? By by modifying the codes ?

**Comment by wangxueping78** [comment]
@lkeab  I found class-agnostic detector and class-aware detector  on the Internet, for this problem, I need to change the detector?

**Comment by lkeab** [comment]
just change the mask head setting. It's not necessary to change the whole detector.

**Comment by wangxueping78** [comment]
> just change the mask head setting. It's not necessary to change the whole detector.
In which code should I change the mask head setting？Can you give some hints？

**Comment by lkeab** [comment]
[here](https://github.com/lkeab/BCNet/blob/b0d3d402bd/detectron2/config/defaults.py#L329)

**Comment by wangxueping78** [comment]
> You can set it [here](https://github.com/lkeab/BCNet/blob/b0d3d402bd/detectron2/config/defaults.py#L329)
Ok,thanks.
