### ISSUE TITLE
Can you tell me your system information?

### ISSUE THREAD

**Issue by CallMeDek** [lkeab/BCNet#111]
Hi @lkeab 

I am following the installation guide to train my own model. 
Unfortunately, I have to use Docker because of other programs' dependencies(CUDA, cudnn etc.)
So I guessed your system used CUDA 10.1, cudnn8, Ubuntu18.04 and tried it. 
But I got an error like below:
![스크린샷, 2022-05-20 15-53-59](https://user-images.githubusercontent.com/22671339/169470727-52cf3985-3fa7-48ad-a2bd-d5a3a5886234.png)
I downloaded coco2017 data and converted to fit your input format using process.sh.
Con you tell me the details of your system info and any tips for it?

Thanks

**Comment by lkeab** [comment]
what's your GPU type?

**Comment by CallMeDek** [comment]
I have four Tesla V100 32G and I resolved that issue after checking out the link. Thanks.
But another problem happened. I think it's because version of each program doesn't match.
Could you tell me (1) CUDA version (2) cudnn version (3) OS (4) gcc version ? 
It's gonna be very helpful for me to handle this problem.

Thanks

**Comment by lkeab** [comment]
1)10.1) 2)cuDNN 7.6.5 3)Center OS 4)GCC 6.3.0

**Comment by CallMeDek** [comment]
Thank you for your help. 
I will try it again with the info

Thanks
