### ISSUE TITLE
There's no prediction during evaluation

### ISSUE THREAD

**Issue by CallMeDek** [lkeab/BCNet#114]
Hi @lkeab 

I always thank for your help. 
Btw, I have a situation. 
The result shows me that there's no prediction during evaluation.
![cap1](https://user-images.githubusercontent.com/22671339/173306183-6327e362-9529-433b-927c-9c2579224101.PNG)
![cap2](https://user-images.githubusercontent.com/22671339/173306218-f7c70292-b23d-449f-96d2-54e8bd9cfcae.PNG)
I think training is fine but I am a little confused if it is a model performance problem or code error.
How do you think about this? Any tips for this?

Thanks

**Comment by lkeab** [comment]
is 99 iterations sufficient for model learning? (what about evaluating after 2000 iterations). Also, pay attention to the matching between model weights and  config file.
