### ISSUE TITLE
heatmaps

### ISSUE THREAD

**Issue by MichelleSchaaf** [lkeab/BCNet#118]
Hey,
I am trying to obtain the heatmaps during classification. Do you have any hints for me on how to do this?
I have also tried to save them during the training process when calculating the keypoint_rcnn_loss, but the DefaultTrainer does not seem to calculate it and therefore does not save the heatmaps.

Kind regards and many thanks,
Michelle :-)

**Comment by lkeab** [comment]
You can use some code lines like this [here](https://github.com/lkeab/BCNet/blob/main/demo/predictor.py#L55): 

```
mask = instances.pred_masks.squeeze(1).data.cpu().numpy()
for i_m in range(len(mask)):
      heatmapshow = cv2.applyColorMap((mask[i_m] * 255).astype(np.uint8), cv2.COLORMAP_JET)
      cv2.imwrite(str(i_m)+"_heatmap_n.jpg", heatmapshow)
```
