### ISSUE TITLE
Training of BCNet with Mask R-CNN

### ISSUE THREAD

**Issue by MichelleSchaaf** [lkeab/BCNet#119]
Hey, I'm trying to train the BCNet with Mask R-CNN and a ResNet-101 backbone, using this [config](configs/COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x.yaml) from Detectron2. It loads the model perfectly and starts the training, however, it immediatly stops the training (0 iterations) and starts the evaluation. The training on the [FCOS config](configs/fcos/fcos_imprv_R_101_FPN.yaml) you provided, works perfectly. 

Any suggestions why this might be?

**Comment by lkeab** [comment]
"it immediatly stops the training (0 iterations) and starts the evaluation." indicates there are training errors (you can wait the evaluation finishing to check the errors). For using MRCNN, you can refer to the discussion [here](https://github.com/lkeab/BCNet/issues/81).
