### ISSUE TITLE
Visualizaiton result is pretty bad.

### ISSUE THREAD

**Issue by willpat1213** [lkeab/BCNet#124]
Thanks for such great job!
I have some trouble in visualization.
Run the code "bash visualization.sh" to visualize segm results.
```
CUDA_VISIBLE_DEVICES=0 python3 demo/demo.py --config-file configs/fcos/fcos_imprv_R_101_FPN.yaml --input ./demo/test_img.jpg --output ./demo/result_img --opts MODEL.WEIGHTS ./pretrained_models/model_final_beta.pth
```
The visualize results as:
![000000000285](https://user-images.githubusercontent.com/69834766/210482698-11300018-7e47-4f24-96b0-366ac36478ac.jpg)

The repo refer to https://github.com/Shadercloud/detectron2
The weight refer to https://hkustconnect-my.sharepoint.com/:u:/g/personal/lkeab_connect_ust_hk/EfiDFLLEawFJpruwuOl3h3ABBjAKysTf0qJQU80iaKbqYg?e=igzC51
I have no idea if need to train the model then visualize.

**Comment by lkeab** [comment]
because you use the repo provided by The repo refer to https://github.com/Shadercloud/detectron2, you should also employ the pretrained model by it. Our provided model is using FCOS detector.

**Comment by willpat1213** [comment]
I took a look at the config and code of this repo, which also uses fcos, but it seems that it does not match the weight model you provided. Is it because the version of D2 is different or the implementation is different?

The details of the visualization process are shown in the figure:

![image](https://user-images.githubusercontent.com/69834766/211449302-5a3ed128-2844-465c-822f-ea067d3711c7.png)

The infer.sh: 
```
CUDA_VISIBLE_DEVICES=0 python3 demo/demo.py --config-file configs/fcos/fcos_imprv_R_101_FPN.yaml \
  --input ./demo/test_img/ \
  --output ./demo/result_img/ \
  --opts MODEL.WEIGHTS ./pretrained_models/model_final_beta.pth
```
