### ISSUE TITLE
results on custom dataset

### ISSUE THREAD

**Issue by trungpham2606** [lkeab/BCNet#13]
Hello @lkeab ,
I was training your BCNet with my dataset. The results are not so good, but the thing I dont understand is that for some cases, the occluders are not detected as you can see my pictures below:
![image](https://user-images.githubusercontent.com/35657426/118390417-2d1aae80-b659-11eb-8563-869d5ff8c68d.png)
![image](https://user-images.githubusercontent.com/35657426/118390441-50ddf480-b659-11eb-9a15-e45fa6dc5c2e.png)
![image](https://user-images.githubusercontent.com/35657426/118390482-79fe8500-b659-11eb-89c0-0a89765e9e42.png)

**Comment by lkeab** [comment]
You could try to lower the detection confidence scores in visualization. Also, I think doing multi-scale training and flip during training might be useful in your cases.

**Comment by trungpham2606** [comment]
@lkeab 
I will try training with augmentation.

**Comment by trungpham2606** [comment]
@lkeab 
I had used augmentation for re-training BCNet. The problem still occurs in some images:
![image](https://user-images.githubusercontent.com/35657426/118431875-7de5e200-b701-11eb-8dbc-7a2fc71b6681.png)
it's quite weird. 
I had set the score_threshold to 0.3

**Comment by lkeab** [comment]
Could you lower the threshold in case the missing one has low confidence score?

**Comment by lkeab** [comment]
I closed the issue since no instant response, you could still leave comments here.

**Comment by trungpham2606** [comment]
@lkeab 
I still not able to figure out why after so many epochs I trained (with augmentation as you suggested), the score for the front object is so slow (around 0.1) ?
![image](https://user-images.githubusercontent.com/35657426/119253079-a70ee280-bbd9-11eb-8804-b87f140373b3.png)
