### ISSUE TITLE
What is the results of your model on COCO 1x training?

### ISSUE THREAD

**Issue by lxtGH** [lkeab/BCNet#16]
Hi! what is mask ap results for 1x training of BCNet using mask-rcnn?

**Comment by lxtGH** [comment]
Aslo, for fair comparison, 3x PointRend can achieve 38.0 on val set (38.2 on test dev) using detectron2. Why your PointRend result is 36.3 since your model come from 3x traing?

**Comment by lkeab** [comment]
> Hi! what is mask ap results for 1x training of BCNet using mask-rcnn?

I remembered that I did't test a 1x training Faster R-CNN on coco-test-dev. The results of PointRend would be corrected after my further checking. I am in a very tight paper ddl these days, and will further response your question under this issue after it.

**Comment by lkeab** [comment]
https://arxiv.org/pdf/2105.11668.pdf
I think it may miss a comparison on coco-test-dev. Since both methods are using boundary for instance segmentation. We have released our 3x training checkpoint and results.

**Comment by lxtGH** [comment]
I will cite all your work.
