### ISSUE TITLE
error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by wanxinjun** [lkeab/BCNet#18]
error: command 'gcc' failed with exit status 1

**Comment by lkeab** [comment]
Could you provide a more detailed description? such as at which installing step it occurs?

**Comment by wanxinjun** [comment]
Hello, I did not expect your reply so quickly, thank you very much.I got such an error while performing the installation process marked in the figure.
![MUZF9PSR4K0)RKEF`H4QJ 6](https://user-images.githubusercontent.com/57660253/119285776-66fd3d80-bc75-11eb-8c91-aaf512cd087d.png)

**Comment by lkeab** [comment]
What's your pytorch and cuda version? The same as our instructions? Also, it would be better to provide more context of the error such as a screen shot etc.

**Comment by lkeab** [comment]
Maybe try pytorch>=1.5 or cuda<=10.1; I don't meet this error personally.
