### ISSUE TITLE
 Extension problem！

### ISSUE THREAD

**Issue by A-good-kids** [lkeab/BCNet#20]
First of all, thank you for your outstanding work. What should I do if I want to use your bcnet module elsewhere? I think if it succeeds, it will be of great help to me.

**Comment by lkeab** [comment]
Thanks for watching our work. Could you be more specific? A simple idea is to extend it to solve other related vision tasks where occlusion is a big issue.

**Comment by lkeab** [comment]
such as pose estimation, 3d related problem or optical flow etc.

**Comment by A-good-kids** [comment]
Thanks for you answer,I want to know where is the code in this part of the picture?I want to use it in my own work.
![2021-05-29 11-08-58屏幕截图](https://user-images.githubusercontent.com/65146982/120056430-b88b3b00-c06e-11eb-8dae-a9563d46e0ce.png)

**Comment by lkeab** [comment]
Please check Line 239 to Line 452 of https://github.com/lkeab/BCNet/blob/main/detectron2/modeling/roi_heads/mask_head.py, which contains the major part of mask head design.
