### ISSUE TITLE
你好，请问下这个代码能在单个gpu下训练吗，还有能在win系统下复现吗？我是科研小白，请多多见谅！

### ISSUE THREAD

**Issue by YeJiaJun321** [lkeab/BCNet#21]

**Comment by lkeab** [comment]
Our code support single gpu training, just modifying the --num-gpus in all.sh. I have not tried Win system, you may refer to [windows compiled detectron2](https://github.com/conansherry/detectron2).

**Comment by YeJiaJun321** [comment]
OK, thank you for your warm reply! I'm going to install an Ubuntu system to run through your code. At present, I still want to know if I can replace it with my own data set for training?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lei ***@***.***&gt;; 
发送时间: 2021年5月26日(星期三) 晚上9:22
收件人: ***@***.***&gt;; 
抄送: "唩の訫飞鴹 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lkeab/BCNet] 你好，请问下这个代码能在单个gpu下训练吗，还有能在win系统下复现吗？我是科研小白，请多多见谅！ (#21)





 
Our code support single gpu training, just modifying the --num-gpus in all.sh. I have not tried Win system, you may refer to windows compiled detectron2.

**Comment by lkeab** [comment]
Sure, you can refer to the closed issue #8 and #13. The core idea is to convert your own dataset similar to coco format using script process.sh.
