### ISSUE TITLE
bilayer occlusion modeling

### ISSUE THREAD

**Issue by anaanaa** [lkeab/BCNet#22]
您好，请问一下，ROI之后那部分遮挡和被遮挡部分的代码在那一块啊，还尚未开源吗

**Comment by lkeab** [comment]
Thanks for your question. Please check Line 239 to Line 452 of https://github.com/lkeab/BCNet/blob/main/detectron2/modeling/roi_heads/mask_head.py, which contains the major part of mask head design.

**Comment by trqminh** [comment]
Hi @lkeab,
I am new to the topic of segmentation. What do heads mean in a segmentation model? This term makes me confuse and I can't search for its definition anywhere else.
Thank you for your consideration.

**Comment by lkeab** [comment]
Head is an opposite concept to the backbone and it is used for predicting the bounding box locations, masks for each object in the image based on the backbone extracted image features. You could regard the head identical as separate prediction branch. Usually we have detection head and mask head in segmentation models.

**Comment by trqminh** [comment]
Thank you a lot.
