### ISSUE TITLE
ValueError: Unknown CUDA arch (8.0) or GPU not supported

### ISSUE THREAD

**Issue by JR-Wang** [lkeab/BCNet#23]
When I tried python3 setup.py build develop, an error occured as follow
ValueError: Unknown CUDA arch (8.0) or GPU not supported
I tried on both V100, CUDA 11.2 and 1060ti, CUDA 11.2, this error always exists.
What should I do?
Many thanks.

**Comment by JR-Wang** [comment]
I use docker to build my environment, so I use pip install pytorch==1.4.0 torchvision==0.5.0, but I print torch.cuda.version, it is as follow:
'10.1'
Does this matter? Must I use conda to build environment?

**Comment by lkeab** [comment]
no, conda is not a must. I conduct experiment on RTX 1080Ti and 2080. not sure whether it is gpu related problem or not.
