### ISSUE TITLE
python3 setup.py build develop

### ISSUE THREAD

**Issue by casialixiaodong** [lkeab/BCNet#24]
Hi, I'm really excited about your work. But now I'm meeting this problem. Is this a proper situation？If not，how I can solve the problem？Thank you.
![image](https://user-images.githubusercontent.com/71364330/120060845-a7e9bd80-c08c-11eb-85b4-64162ab62892.png)

**Comment by lkeab** [comment]
Maybe you need to downgrad the gcc version as [here](https://github.com/facebookresearch/detectron2/issues/1459).  I use gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11).

Downgrading (switching compiler) gcc 7.5.0 to 5.5.0 :
For those wondering about the downgrade process, here is how I did it on Ubuntu 18.04.4:

1. Install gcc-5 and g++-5
you may already have it installed at /usr/bin/gcc-5
sudo apt install gcc-5
sudo apt install g++-5

2. Switch the default compiler to version 5
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 5
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 5
