### ISSUE TITLE
[feature request] script for transforming coco-dataset to required?

### ISSUE THREAD

**Issue by heizie** [lkeab/BCNet#26]
Thank you for the code.
```
Prepare for coco2017 dataset following this instruction. And use our converted mask annotations to replace original annotation file for bilayer decoupling training.
```
It is possible to share the script for transforming coco-format to such a format?
Or could you explain, what exactly be done for these "converted mask"?

**Comment by lkeab** [comment]
Please refer to [process.sh](https://github.com/lkeab/BCNet#reference-script-for-producing-bilayer-mask-annotation).
