### ISSUE TITLE
pretrained weights 

### ISSUE THREAD

**Issue by trungpham2606** [lkeab/BCNet#3]
Thank your @lkeab for sharing such a great work !
Where can I download the pretrained weights ?

**Comment by lkeab** [comment]
Hi, thanks for watching! The pretrained model is currently under preparation. I will release it before cvpr and update the project page.

**Comment by lkeab** [comment]
The pretrained weights is available now.

**Comment by trungpham2606** [comment]
@lkeab 
Thank for sharing your pretrained weights.
I had tested it on coco. But the results I achieve are pretty bad
![image](https://user-images.githubusercontent.com/35657426/114302880-52b21680-9af5-11eb-9c94-431381a29579.png)
![image](https://user-images.githubusercontent.com/35657426/114302894-63fb2300-9af5-11eb-8bd3-44e3ce0ef67d.png)
![image](https://user-images.githubusercontent.com/35657426/114302915-82f9b500-9af5-11eb-9735-cde97c9abae1.png)

**Comment by lkeab** [comment]
That's strange and I think it may due to your visualization setting. I tested it again and my visulization result is like following pic
![image](https://user-images.githubusercontent.com/17427852/114313416-05e83300-9b29-11eb-9106-937a7aa4a236.png)

**Comment by lkeab** [comment]
Please use "bash visualize.sh" to have a try.

**Comment by trungpham2606** [comment]
@lkeab 
Thank you for your prompt response. Iam gonna test it again right now.
