### ISSUE TITLE
怎么测试单张图片(How to test single image)

### ISSUE THREAD

**Issue by szh91** [lkeab/BCNet#30]

**Comment by lkeab** [comment]
Please refer to the [issue 17](https://github.com/lkeab/BCNet/issues/17)

**Comment by szh91** [comment]
我把要测试的图片放在test_img下，然后运行sh visualize.sh 后报错
WARNING [06/18 20:07:44 d2.config.compat]: Config 'configs/fcos/fcos_imprv_R_101_FPN.yaml' has no VERSION. Assuming it to be compatible with latest v2.
['test_img/']
Segmentation fault (core dumped)

**Comment by lkeab** [comment]
What's your pytorch and cuda version? The same as our instructions? Also, it would be better to provide more context of the error such as a screen shot etc.

**Comment by szh91** [comment]
cuda 10.0， pytorch 1.4.0， torchvision 0.5.0，
![image](https://user-images.githubusercontent.com/30435832/122661117-9f7f3100-d1b9-11eb-940b-135b7963249d.png)

**Comment by lkeab** [comment]
Please check the solution [here](https://github.com/facebookresearch/detectron2/issues/62#issuecomment-542447753), which will be helpful.

**Comment by lkeab** [comment]
Or in this [3](https://github.com/facebookresearch/detectron2/issues/260)

**Comment by szh91** [comment]
感谢大佬耐心回答，您的意思是我先要安装detectron2？然后才能运行代码吗，这个detectron2是安装这个目录下还是？

**Comment by lkeab** [comment]
yes in this directory as long as it could be found

**Comment by szh91** [comment]
大佬好，我也尝试了安装detectron2然后试了还是出错，昨晚重新按照你的教程，依旧报同样的错误，可以加你微信吗？

**Comment by wuxiangrui188** [comment]
> 大佬好，我也尝试了安装detectron2然后试了还是出错，昨晚重新按照你的教程，依旧报同样的错误，可以加你微信吗？

大佬，你解决了吗？
