### ISSUE TITLE
Data conversion

### ISSUE THREAD

**Issue by tangmao2019** [lkeab/BCNet#31]
Thank you for the code.
How do I convert the standard coco file format into the json format usable by BCNet?
How to get bg_object_segmentation in the json file available on BCNet？There are 3700 instances in the training data.
 
[06/22 21:13:16 d2.engine.train_loop]: Starting training from iteration 0
[06/22 21:13:16 d2.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)

**Comment by lkeab** [comment]
Thanks for watching our work. Please refer to [process.sh](https://github.com/lkeab/BCNet#reference-script-for-producing-bilayer-mask-annotation).

**Comment by tangmao2019** [comment]
Thank you for your answer. I have solved the problem of the data set, but I encountered a new problem during training. The training time of all images is 0 seconds, and then I started to infer. Can I ask what the possible reason is ?

**Comment by lkeab** [comment]
It means there is training error and the models skips this training stage to do evaluation.
