### ISSUE TITLE
Can BCNet cut out letters from a manuscript?

### ISSUE THREAD

**Issue by SB2020-eye** [lkeab/BCNet#32]
Hi.

I am very much a beginner, so please bear with me if I am not very technical or precise. (I'll do my best to be clear! 🙂 )

I'm working on a project where I want to cut out all individual letters from images of a long manuscript. One line of a page looks a lot like this:
![Chad_one_line](https://user-images.githubusercontent.com/56878280/123270485-f2b0f680-d4cd-11eb-8192-b7d06efca75f.png)

I want to cut out each letter, with no background -- like this, for example:
![Chad_one_word e](https://user-images.githubusercontent.com/56878280/123271413-cb0e5e00-d4ce-11eb-9005-bfee340e1d30.png)

I am wondering:

If I provided enough annotations for each letter, would BCNet be able to accomplish my goal? Or would you recommend some other route?

**Comment by lkeab** [comment]
For this task, I think the object detection accuracy is critical. You need to provide bbox for each character and the masks, and then BCNet could segment it.

**Comment by SB2020-eye** [comment]
Okay. Thank you very much.
