### ISSUE TITLE
数据转化

### ISSUE THREAD

**Issue by liujie1202** [lkeab/BCNet#33]
你好，现在builtin_meta.py中修改了things_classes,添加了自己的数据集，但是再执行bash process.sh时，出现了process_datasets中的错误，这个数据集转换之间的几个文件的关系没太明白，一直没有将自己的数据集转化成功，能帮忙解答一下吗，谢谢！
![QQ图片20210625202952](https://user-images.githubusercontent.com/83169458/123426109-91844280-d5f5-11eb-874b-1fbbdf614a71.png)
![QQ图片20210625202945](https://user-images.githubusercontent.com/83169458/123426115-934e0600-d5f5-11eb-8fac-ecf50066bb67.png)

**Comment by lkeab** [comment]
Please register your new dataset name [here](https://github.com/lkeab/BCNet/blob/5c036d4b65883afc077ebb6cd1cc579caef77ad4/detectron2/data/datasets/builtin.py#L32)

**Comment by EVXEVXYA** [comment]
@liujie1202 你好，请问你解决了更换新的数据集这个问题吗？我想使用自己的数据集进行训练，更改了things_classes，也在他说的那个位置进行了数据集注册，运行process.sh还是会报错，是不是还有其他参数需要更改？
