### ISSUE TITLE
This is an exciting result, but I would like to ask where can I download the newly synthetic occlusion images? I only find the new annotations find the annontion

### ISSUE THREAD

**Issue by lcc157** [lkeab/BCNet#36]

**Comment by lkeab** [comment]
The new annotations [here](https://github.com/lkeab/BCNet#dataset-preparation) for coco does not need synthetic occluded images, just using the normal coco images for training. For deep understanding of our method, you could refer to [here](https://github.com/lkeab/BCNet/issues/11#issuecomment-841707227).
