### ISSUE TITLE
How to visualize GCN layer on Images? 

### ISSUE THREAD

**Issue by shekharidentv** [lkeab/BCNet#38]
bear with me for the question, wanted to visualize this part in any images. 

![image](https://user-images.githubusercontent.com/53888835/125509472-796fb2e4-785a-49d1-9254-5f2f6c65ed9c.png)

**Comment by lkeab** [comment]
By using matplotlib to visualize the four variables [here](https://github.com/lkeab/BCNet/blob/main/demo/predictor.py#L51)
