### ISSUE TITLE
Results Question

### ISSUE THREAD

**Issue by seokmin-kim** [lkeab/BCNet#4]
Hi! Thisi is a very insteresting paper. I have a question on results comparison.
In Table 6. Results of the KINS dataset, 
AP_seg of Mask R-CNN + ASN : 25.62
AP_seg of PANet + ASN  : 26.81

But in [46]Amodal instance segmentation with kins dataset, 
AP_seg of Mask R-CNN + ASN : 31.1
AP_seg of PANet + ASN  : 32.2

AP_Det values are also different. 

Why these results are different?

**Comment by lkeab** [comment]
Hi, thanks for the question. I think it is due to the selection of different backbone networks, like resnet-50 and resnet-101 etc, which is not detailed in their paper. Thus, I obtained the results by running their official code for comparison.
