### ISSUE TITLE
前景提取 (Foreground extraction)

### ISSUE THREAD

**Issue by ccq195** [lkeab/BCNet#40]
作者您好。感谢的开源。我配置好了您的代码，运行了您的visual.sh，效果非常好。就是请问修改哪部分代码能实现前景提取呢？我需要剔除图像中的背景信息。

**Comment by lkeab** [comment]
Hi, thanks for watching our work. You could access the predicted binary mask here [here](https://github.com/lkeab/BCNet/blob/main/demo/predictor.py#L51) and the strategy is to multiply the image with these extracted masks.
