### ISSUE TITLE
python3 setup.py build develop

### ISSUE THREAD

**Issue by DonaldKam** [lkeab/BCNet#42]
Great job! But I failed in Step **python3 setup.py build develop**. The errors are as follow:
![image](https://user-images.githubusercontent.com/44252954/127277156-443febac-ce02-432e-b481-b1fda303ee37.png)
![image](https://user-images.githubusercontent.com/44252954/127277354-37196985-bf4f-4b30-867e-92af51d792cb.png)
My Linux environment is: RTX3090, CUDA11.1, Pytorch1.7.
I would be greatly appreciated if you could spend some of your time solving the problem for me. I am very pleased to hear from you.
@lkeab

**Comment by lkeab** [comment]
For the "AT_check" problem, please try：
`
#ifndef AT_CHECK
#define AT_CHECK TORCH_CHECK 
#endif
`

**Comment by lkeab** [comment]
There is similar discussion on how to use detectron2 on RTX 3090 [here](https://github.com/facebookresearch/detectron2/issues/2325) and [here](https://github.com/facebookresearch/detectron2/issues/2225). Personally, I have not tried that new GPU architecture but I think [this](https://github.com/facebookresearch/detectron2/issues/2225#issuecomment-724942979) may help.

**Comment by lkeab** [comment]
I think the easiest way is to : 1) download the lastest detectron2 with pytorch1.8 and make sure it works in the running environment. 2) replace the dataloader, config file, maskhead file of the lastest detectron2 with the codes in BCNet repo.
