### ISSUE TITLE
Confuse about the training details of mask head

### ISSUE THREAD

**Issue by EDENpraseHAZARD** [lkeab/BCNet#43]
Dear author:
Thanks for your great job!
I'm confused about the training details of mask head. I find that you use the roi_feat extracted from gt_bbox instand of pred box from FCOS to train maskhead, right? 

![image](https://user-images.githubusercontent.com/53077461/127472816-664c54e2-26cc-4d3b-a803-39a4237b8adc.png)

In './fcos.py', you always add gt to proposals and do the match between proposals and gt. So the 'gt' added to proposals will 100%  match the gt. Then in the 'self._sample_proposals' function, I find that it's not a sample function, it just return the index of matched proposal（which is the gt added to proposals）. Finally, I print out the proposal boxes which will be the input of maskhead, and I find it's the same as gt_box.

![gt pred](https://user-images.githubusercontent.com/53077461/127473713-c0212796-d214-4117-af0e-02b750d87a9c.PNG)

In the code comments, you say that when training starts the proposals will be low quality due to random initialization, so you add gt. But it will cause the input of maskhead is always the roi from gt_box.

**Comment by lkeab** [comment]
which checkpoint did you use? training from scratch?

**Comment by EDENpraseHAZARD** [comment]
![image](https://user-images.githubusercontent.com/53077461/127512781-96a0c2bf-2a26-44aa-9a39-f491c21ac699.png)

No matter which checkpoint i used, the roi is always extracted by gt_box

**Comment by lkeab** [comment]
I guess it is because during the initial stage the box proposal has a lower quality but the box quality will be gradually improved during training.

**Comment by lkeab** [comment]
Your printed box proposal number is very small. Only 2 or 3 which means lot of proposals are not matched.

**Comment by EDENpraseHAZARD** [comment]
Actually, FCOS will predict 100 proposals for each img. For example, an img have 11 gt instances. In 'label_and_sample_proposals' function, gt box have been added to proposals, so we get 111 proposals. Then 'pairwise' function will return a 11*111 matrix. And the gt added to proposals must match target gt. No matter how good the pred box quality is, the added gt must be better than it. Thus, no pred box will be used for mask head.

In common rcnn roi head, such as maskrcnn, it also used gt_added_to_proposals, but its sample function is different from yours. It randomly sample positive and negative proposals for box head and only positive samples for maskhead which will contain the pred box . But in BCNet, I find the sample function just return the proposals successfully matched gt. So I'm confused whether I have wrong understanding of your code.

**Comment by EDENpraseHAZARD** [comment]
Oh, I get it. It means gt may match several proposals so the good quality pred box will also match. It is same as common roi head.
Thanks a lot !
By the way, will you release the code of faster-rcnn+BCNet?

**Comment by lkeab** [comment]
It is contained in the code [here](https://github.com/lkeab/BCNet/blob/main/detectron2/modeling/roi_heads/fast_rcnn.py). You just need to modify the config to use faster rcnn instead of fcos as object dectecter.

**Comment by EDENpraseHAZARD** [comment]
Thanks a lot

**Comment by cp1108** [comment]
> Thanks a lot

Do you have config of faster-rcnn+BCNet？Thanks a lot
