### ISSUE TITLE
Full mask for occludees

### ISSUE THREAD

**Issue by trqminh** [lkeab/BCNet#49]
Hi @lkeab ,
Thank you for your consideration.
From the [issue 28](https://github.com/lkeab/BCNet/issues/28)
Regarding the question "every object will have a full mask no matter they are occluder or occludee?", it is yes for the amodal task.

I would like to ask about the COCO-OCC, is that split has full masks for every object from the beginning? If not, how you can conduct the mask for the ocludees?

**Comment by lkeab** [comment]
COCO-OCC is a split of COCO (overlapping ratio between the bounding boxes of
objects is at least 0.2), which is for not for amodal segmentation thus does not require full masks for occludees. In this standard instance segmentation, we only use the visible masks for the occludees (provided in coco annotation). For more, you could refer to the discussion [here](https://github.com/lkeab/BCNet/issues/11).

**Comment by trqminh** [comment]
Thank you for your answer.

**Comment by chengfengruan** [comment]
Therefore, the boundary supervision of the occludees is also an incomplete boundary, isn't it?

**Comment by lkeab** [comment]
for normal instance segmentation, yes.
