### ISSUE TITLE
train new dataset

### ISSUE THREAD

**Issue by trungpham2606** [lkeab/BCNet#5]
Dear @lkeab,
I have tested successfully your model on coco dataset. Nevertheless, I also want to fine-tune the model on my custom dataset.
Can you provide the script to change the coco format to BCnet format or give me the pipeline of the dataset format ?

**Comment by lkeab** [comment]
I need take some time to organize it. Once it is done, I will update the readme page.

**Comment by lkeab** [comment]
Please refer to the reference script **process.sh** in the new readme file.
