### ISSUE TITLE
about the first GCN layer

### ISSUE THREAD

**Issue by tangmao2019** [lkeab/BCNet#52]
Thank you for your work. We have obtained good results using this network, but there are still some questions.

How to ensure that what is obtained in the first GCN network layer is the position and shape information of the occluder? Will there be a situation where what is detected in the first layer of GCN is the occludee?

**Comment by lkeab** [comment]
This is ensured by training with bilayer annotations. For the 2nd question, please refer to the discussion [here](https://github.com/lkeab/BCNet/issues/11).

**Comment by tangmao2019** [comment]
非常感谢您的回答，还有另一个问题想要问一下您。
在计算特征相似度时，特征图上的像素点要和周围多少个像素点去计算相似度呢，只需要和一个点计算还是需要和多个像素点计算相似度呢？
如果只和周围一个像素点计算相似度，如何保证在仅经过一次GCN就可以得到全局特征呢？
![1631089629](https://user-images.githubusercontent.com/49310125/132474970-c10ed49c-0c5a-419a-9243-a437d22db6ce.jpg)

**Comment by lkeab** [comment]
One pixel needs to compute with all other pixels in the ROI. (2)(3) are the formulas for computing between **every two points**.
