### ISSUE TITLE
RuntimeError: CUDA error: invalid device function (ROIAlign_forward_cuda at

### ISSUE THREAD

**Issue by coderrubbish** [lkeab/BCNet#55]
nice work！ I have a problem with the training program,  I follow the requirements in the readme to create the environment, when i run the all.sh, I get an error.  I search for a solution to this error and try to install the mmcv-full. It still can't work.  Could you give me some suggestions？ Thanks

**[09/18 21:53:11 d2.data.common]: Serializing 5000 elements to byte tensors and concatenating them all ...
[09/18 21:53:11 d2.data.common]: Serialized dataset takes 19.39 MiB
[09/18 21:53:12 d2.evaluation.evaluator]: Start inference on 2500 images**
Traceback (most recent call last):
  File "tools/train_net.py", line 161, in <module>
    args=(args,),
  File "/home/wangmeili/zhk/bcnet/BCNet/detectron2/engine/launch.py", line 48, in launch
    daemon=False,
  File "/home/wangmeili/anaconda3/envs/hkbcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/wangmeili/anaconda3/envs/hkbcnet/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/wangmeili/zhk/bcnet/BCNet/detectron2/engine/train_loop.py", line 131, in train
    self.run_step()
  File "/home/wangmeili/zhk/bcnet/BCNet/detectron2/engine/train_loop.py", line 211, in run_step
    loss_dict = self.model(data, self.iter, self.max_iter)
  File "/home/wangmeili/anaconda3/envs/hkbcnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wangmeili/anaconda3/envs/hkbcnet/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/wangmeili/anaconda3/envs/hkbcnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wangmeili/zhk/bcnet/BCNet/detectron2/modeling/meta_arch/fcos.py", line 176, in forward
    centerness, gt_instances, batched_inputs, images, c_iter, max_iter
  File "/home/wangmeili/zhk/bcnet/BCNet/detectron2/modeling/meta_arch/fcos.py", line 199, in _forward_train
    loss_mask, loss_mask_bo, loss_boundary, loss_boundary_bo = self._forward_mask(features_list, proposals)
  File "/home/wangmeili/zhk/bcnet/BCNet/detectron2/modeling/meta_arch/fcos.py", line 245, in _forward_mask
    mask_features = self.mask_pooler(features, proposal_boxes)
  File "/home/wangmeili/anaconda3/envs/hkbcnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wangmeili/zhk/bcnet/BCNet/detectron2/modeling/poolers.py", line 232, in forward
    output[inds] = pooler(x_level, pooler_fmt_boxes_level)
  File "/home/wangmeili/anaconda3/envs/hkbcnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wangmeili/zhk/bcnet/BCNet/detectron2/layers/roi_align.py", line 94, in forward
    input, rois, self.output_size, self.spatial_scale, self.sampling_ratio, self.aligned
  File "/home/wangmeili/zhk/bcnet/BCNet/detectron2/layers/roi_align.py", line 19, in forward
    input, roi, spatial_scale, output_size[0], output_size[1], sampling_ratio, aligned
**RuntimeError: CUDA error: invalid device function (ROIAlign_forward_cuda at /home/wangmeili/zhk/bcnet/BCNet/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.cu:361)**
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f5cfe3e2193 in /home/wangmeili/anaconda3/envs/hkbcnet/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: detectron2::ROIAlign_forward_cuda(at::Tensor const&, at::Tensor const&, float, int, int, int, bool) + 0xa37 (0x7f5ce1192345 in /home/wangmeili/zhk/bcnet/BCNet/detectron2/_C.cpython-37m-x86_64-linux-gnu.so)
frame #2: detectron2::ROIAlign_forward(at::Tensor const&, at::Tensor const&, float, int, int, int, bool) + 0xbc (0x7f5ce112f78c in /home/wangmeili/zhk/bcnet/BCNet/detectron2/_C.cpython-37m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x6ab35 (0x7f5ce1140b35 in /home/wangmeili/zhk/bcnet/BCNet/detectron2/_C.cpython-37m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x6ac5e (0x7f5ce1140c5e in /home/wangmeili/zhk/bcnet/BCNet/detectron2/_C.cpython-37m-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x654b0 (0x7f5ce113b4b0 in /home/wangmeili/zhk/bcnet/BCNet/detectron2/_C.cpython-37m-x86_64-linux-gnu.so)
frame #6: _PyMethodDef_RawFastCallKeywords + 0x217 (0x558a677bd867 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #7: <unknown function> + 0x16e0b8 (0x558a678190b8 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #8: _PyEval_EvalFrameDefault + 0x4c9a (0x558a678625ea in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #9: _PyFunction_FastCallDict + 0x19d (0x558a677a336d in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #10: THPFunction_apply(_object*, _object*) + 0xa7f (0x7f5cb889a3ef in /home/wangmeili/anaconda3/envs/hkbcnet/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #11: _PyMethodDef_RawFastCallKeywords + 0x1db (0x558a677bd82b in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #12: <unknown function> + 0x16e0b8 (0x558a678190b8 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #13: _PyEval_EvalFrameDefault + 0x96a (0x558a6785e2ba in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #14: _PyFunction_FastCallDict + 0x19d (0x558a677a336d in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #15: <unknown function> + 0x10eb93 (0x558a677b9b93 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #16: PyObject_Call + 0x6c (0x558a677b08dc in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #17: _PyEval_EvalFrameDefault + 0x1f5c (0x558a6785f8ac in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #18: _PyEval_EvalCodeWithName + 0x242 (0x558a677a1fb2 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #19: _PyFunction_FastCallDict + 0x35d (0x558a677a352d in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #20: _PyObject_Call_Prepend + 0x6e (0x558a677b992e in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #21: <unknown function> + 0x207f89 (0x558a678b2f89 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #22: _PyObject_FastCallKeywords + 0x48b (0x558a67818bdb in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #23: <unknown function> + 0x16e139 (0x558a67819139 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #24: _PyEval_EvalFrameDefault + 0x96a (0x558a6785e2ba in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #25: _PyFunction_FastCallDict + 0x19d (0x558a677a336d in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #26: <unknown function> + 0x10eb93 (0x558a677b9b93 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #27: PyObject_Call + 0x6c (0x558a677b08dc in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #28: _PyEval_EvalFrameDefault + 0x1f5c (0x558a6785f8ac in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #29: _PyEval_EvalCodeWithName + 0x242 (0x558a677a1fb2 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #30: _PyFunction_FastCallDict + 0x35d (0x558a677a352d in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #31: _PyObject_Call_Prepend + 0x6e (0x558a677b992e in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #32: <unknown function> + 0x207f89 (0x558a678b2f89 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #33: _PyObject_FastCallKeywords + 0x48b (0x558a67818bdb in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #34: <unknown function> + 0x16e139 (0x558a67819139 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #35: _PyEval_EvalFrameDefault + 0x4c9a (0x558a678625ea in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #36: _PyFunction_FastCallKeywords + 0x184 (0x558a67817e74 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #37: <unknown function> + 0x16dfa8 (0x558a67818fa8 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #38: _PyEval_EvalFrameDefault + 0x4c9a (0x558a678625ea in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #39: _PyFunction_FastCallKeywords + 0x184 (0x558a67817e74 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #40: <unknown function> + 0x16dfa8 (0x558a67818fa8 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #41: _PyEval_EvalFrameDefault + 0x4c9a (0x558a678625ea in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #42: _PyEval_EvalCodeWithName + 0x242 (0x558a677a1fb2 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #43: _PyFunction_FastCallDict + 0x35d (0x558a677a352d in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #44: <unknown function> + 0x10eb93 (0x558a677b9b93 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #45: PyObject_Call + 0x6c (0x558a677b08dc in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #46: _PyEval_EvalFrameDefault + 0x1f5c (0x558a6785f8ac in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #47: _PyEval_EvalCodeWithName + 0x242 (0x558a677a1fb2 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #48: _PyFunction_FastCallDict + 0x35d (0x558a677a352d in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #49: _PyObject_Call_Prepend + 0x6e (0x558a677b992e in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #50: <unknown function> + 0x207f89 (0x558a678b2f89 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #51: PyObject_Call + 0x6c (0x558a677b08dc in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #52: _PyEval_EvalFrameDefault + 0x1f5c (0x558a6785f8ac in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #53: _PyEval_EvalCodeWithName + 0x242 (0x558a677a1fb2 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #54: _PyFunction_FastCallDict + 0x35d (0x558a677a352d in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #55: <unknown function> + 0x10eb93 (0x558a677b9b93 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #56: PyObject_Call + 0x6c (0x558a677b08dc in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #57: _PyEval_EvalFrameDefault + 0x1f5c (0x558a6785f8ac in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #58: _PyEval_EvalCodeWithName + 0x242 (0x558a677a1fb2 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #59: _PyFunction_FastCallDict + 0x35d (0x558a677a352d in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #60: _PyObject_Call_Prepend + 0x6e (0x558a677b992e in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #61: <unknown function> + 0x207f89 (0x558a678b2f89 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #62: _PyObject_FastCallKeywords + 0x48b (0x558a67818bdb in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)
frame #63: <unknown function> + 0x16e139 (0x558a67819139 in /home/wangmeili/anaconda3/envs/hkbcnet/bin/python3)

**Comment by lkeab** [comment]
Could you tell me your Gpu type, Gpu numbers, cuda version and pytorch version?

**Comment by lkeab** [comment]
Please check whether this [answer](https://github.com/facebookresearch/detectron2/issues/62#issuecomment-542447753) would help or not.

**Comment by coderrubbish** [comment]
> 请检查此[答案](https://github.com/facebookresearch/detectron2/issues/62#issuecomment-542447753)是否有帮助。

OK, thanks. Let me try
