### ISSUE TITLE
Training with one custom class

### ISSUE THREAD

**Issue by chauthehan** [lkeab/BCNet#56]
Thanks for the work. I got a problem when training this segmentation model with custom dataset. I have got a coco format dataset with only one class. How can i convert this json file to the format that model can use. I already looked in process_dataset.py, but this file only work for dataset with 80 classes. Please help me. Thanks in advance!

**Comment by lkeab** [comment]
Hi, thanks for watching our work. You could first refer to the discussion [here](https://github.com/lkeab/BCNet/issues/27).

**Comment by chauthehan** [comment]
thank you! It works now
