### ISSUE TITLE
Output mask results

### ISSUE THREAD

**Issue by DonaldKam** [lkeab/BCNet#57]
Hi, I am try to save the mask results output by the model and only to find unreadable code in json file, shown as following:
![image](https://user-images.githubusercontent.com/44252954/134759607-a88b831f-65e0-4598-a557-3ce3ad421150.png)
How to transform the unreadable code into polygons that are defined by vertexes？

**Comment by lkeab** [comment]
Hi, you could to the solution at this [issue](https://github.com/cocodataset/cocoapi/issues/476) on converting mask from RLE format to polygon format.
