### ISSUE TITLE
Prepare for coco2017 dataset following this instruction.

### ISSUE THREAD

**Issue by peppa114** [lkeab/BCNet#60]
![1](https://user-images.githubusercontent.com/83171253/136551995-97f54666-6bcc-4a39-b20c-600754047c2f.png)
Hello, may I ask how to process data in this webpage? Should I choose one of them or all of them？
Thanks！

**Comment by lkeab** [comment]
you just need to choose coco for instance segmentation if experiments are on it

**Comment by peppa114** [comment]
> 嗨，如果有实验，你只需要选择 coco 进行实例分割

thank you !
