### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Kammagod** [lkeab/BCNet#61]
![1](https://user-images.githubusercontent.com/82814491/136641161-3c945c2e-8734-48df-8e06-92d0f6132454.png)
hi,what is this step doing?

Is dataset preparation directly using the following one？
![2](https://user-images.githubusercontent.com/82814491/136641259-9cfa5bbf-0f65-4684-80ee-3c6d82215d5e.png)

What is the format of the final dataset？Which .json files are in the **coco/annotations** folder

thanks!

**Comment by Kammagod** [comment]
> Hi, it should be coco/annotations/instances_{train,val}2017.json. But you need to replace the instances_train2017.json with the annotation provided by us.

I got **instances_val2017_100.json** from **prepare_for_tests.sh**, does **instances_val2017_100.json** here refer to **instances_{val}2017.json** you said?

**Comment by lkeab** [comment]
These two jsons could be downloaded from official coco website directly, which may not require your own processing. You just need to replace the instances_train2017.json with ours.
