### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by AnnaMariaMeer** [lkeab/BCNet#67]
Hi, 

Thank you for your great work. I am quite a beginner and trying to get BCNet to run with the Coco Dataset. In the beginning it runs smoothly over the first iterations. But when starting inference, somehow I get the error RuntimeError: CUDA out of memory. I reduced the batch size in the defaults.py, but somehow it had no effect. 

Thanks in advance :)

**Comment by trqminh** [comment]
Hi @lkeab,
I think it might be relevant to this topic so I want to ask a question here.
In the config file, I set IMS_PER_BATCH=1 and use 1 GPU for training as the following command and it takes 9GB/16GB of my memory:
```
CUDA_VISIBLE_DEVICES=4 python3 tools/train_net.py --num-gpus 1 \
    --config-file configs/minh_entries/${entry_name}.yaml 2>&1 | tee log/train_log_$ID.txt
```
Currently, I add some layers to the mask head, thus, the memory is now out. Then, I set the command as follow to run with 2 GPU:
```
CUDA_VISIBLE_DEVICES=3,4 python3 tools/train_net.py --num-gpus 2 \
     --config-file configs/minh_entries/${entry_name}.yaml 2>&1 | tee log/train_log_$ID.txt
```
but this assertion occurs:
```
AssertionError: SOLVER.IMS_PER_BATCH (1) must be divisible by the number of workers (2).
```
I think It means that I cannot surpass the 16GB of my machine for 1 IMS_PER_PATCH. Can you help me with this issue? Is there any way to train with 1 IMS_PER_PATCH with more than 1 GPU? 

Thank you for your consideration.

**Comment by lkeab** [comment]
you could fix the gradients of partial model params to save memory.

**Comment by AnnaMariaMeer** [comment]
Hi @lkeab, 

I have 3 GPUs with 12GB memory each and I use 2 GPU for training.
