### ISSUE TITLE
Retrain on different dataset

### ISSUE THREAD

**Issue by ssnirgudkar** [lkeab/BCNet#69]
Hello,
I have my own data set which has instance labels. Is it possible to retrain BCNet on a different data set? Are there any assumptions in it which I should be aware of?
Thanks.

**Comment by lkeab** [comment]
yes, you can follow the instructions [here](https://github.com/lkeab/BCNet#reference-script-for-producing-bilayer-mask-annotation) for making your own bilayer annotations.
