### ISSUE TITLE
测试新的数据集

### ISSUE THREAD

**Issue by liujie1202** [lkeab/BCNet#7]
您好，想用自己的数据集测试一下这个方法，想问一下，数据集那部分是需要将coco格式数据集再进行转化吗？应用数据集的那块代码在哪里可以查看呀

**Comment by lkeab** [comment]
Yes, it should be converted to bilayer annotation. The main part for data process is in https://github.com/lkeab/BCNet/blob/main/detectron2/data/datasets/coco.py and https://github.com/lkeab/BCNet/blob/main/detectron2/data/datasets/builtin.py.
