### ISSUE TITLE
Feature map size for mask head

### ISSUE THREAD

**Issue by trqminh** [lkeab/BCNet#70]
Hi @lkeab,

First, I would like to thank you for your constant response to my questions. I have been learning a lot from your work.
My question is that why you chose the ROI pooling spatial feature size to be 14x14. Is it for the memory efficiency or it is the result of doing some sort of grid search or any other insights? I don't know it is a good question or not, hope to see your response.
![image](https://user-images.githubusercontent.com/30286786/140588160-04ef56c9-e34f-4dcf-9cd2-a1b34c1aa2af.png)

Thanks for your consideration.

**Comment by lkeab** [comment]
Hi, thanks for watching our work. This size is J=just for efficiency and it is a default choice by Mask R-CNN.
