### ISSUE TITLE
Training with custom dataset 

### ISSUE THREAD

**Issue by AnnaMariaMeer** [lkeab/BCNet#71]
Hi, I want to train with a custom dataset, but currently I get the error: 

 File "/BCNet/detectron2/data/detection_utils.py", line 185, in transform_instance_annotations
    mask = mask_util.decode(segm)
  File "/anaconda3/envs/bcnet4/lib/python3.7/site-packages/pycocotools/mask.py", line 94, in decode
    return _mask.decode([rleObjs])[:,:,0]
  File "pycocotools/_mask.pyx", line 146, in pycocotools._mask.decode
  File "pycocotools/_mask.pyx", line 128, in pycocotools._mask._frString
TypeError: Expected bytes, got list

I think it is because of my coco RLE segmentation format, but I couldn't fix it until now somehow. Do you maybe have an idea how to solve this issue? 
Thank you so much!

**Comment by lkeab** [comment]
is your annotation a polygon or a compressed RLE?

**Comment by AnnaMariaMeer** [comment]
Hi, my annotation is in a RLE format. The annotation file looks like that:    

"annotations": [
        {
            "id": 1,
            "image_id": 30,
            "bbox": [
                404.0,
                138.0,
                75.0,
                73.0
            ],
            "area": 5475.0,
            "iscrowd": 0,
            "category_id": 1,
            "segmentation": {
                "counts": [
                    194104,
                    1,
                    475,
                    1,
                    3,
                    1,
                    475,
                    5,
                    475,
                    5,
                    475,
                    5,
                    475,
                    5,
                    475,
                    3,
                    477,
                    1,
                    462,
                    1,
                    1,
                    3,
                    470,
                    26,
                    451,
                    30,
                    447,
                    33,
                    445,
                    35,
                    8,
                    1,
                    1,
                    3,
                    3,
                    3,
                    425,
                    36,
                    9,
                    12,
                    422,
                    39,
                    7,
                    14,
                    419,
                    40,
                    7,
                    14,
                    418,
                    41,
                    8,
                    13,
                    417,
                    43,
                    7,
                    14,
                    415,
                    45,
                    4,
                    18,
                    412,
                    47,
                    3,
                    17,
                    413,
                    49,
                    1,
                    17,
                    412,
                    50,
                    3,
                    15,
                    411,
                    53,
                    1,
                    15,
                    411,
                    68,
                    411,
                    69,
                    411,
                    69,
                    411,
                    15,
                    4,
                    50,
                    410,
                    15,
                    5,
                    48,
                    412,
                    14,
                    7,
                    47,
                    412,
                    13,
                    8,
                    47,
                    411,
                    13,
                    9,
                    47,
                    411,
                    13,
                    9,
                    47,
                    411,
                    12,
                    10,
                    47,
                    411,
                    12,
                    10,
                    47,
                    411,
                    11,
                    10,
                    47,
                    412,
                    11,
                    10,
                    47,
                    412,
                    10,
                    11,
                    47,
                    412,
                    10,
                    10,
                    50,
                    410,
                    10,
                    10,
                    50,
                    410,
                    11,
                    9,
                    49,
                    411,
                    10,
                    9,
                    50,
                    411,
                    10,
                    9,
                    49,
                    412,
                    11,
                    8,
                    49,
                    412,
                    13,
                    6,
                    48,
                    413,
                    13,
                    6,
                    47,
                    414,
                    13,
                    6,
                    47,
                    414,
                    13,
                    6,
                    46,
                    416,
                    12,
                    3,
                    49,
                    416,
                    13,
                    1,
                    50,
                    416,
                    64,
                    417,
                    63,
                    417,
                    62,
                    419,
                    61,
                    419,
                    61,
                    419,
                    60,
                    421,
                    59,
                    421,
                    59,
                    422,
                    57,
                    424,
                    56,
                    424,
                    56,
                    425,
                    54,
                    427,
                    52,
                    429,
                    51,
                    430,
                    49,
                    432,
                    47,
                    434,
                    45,
                    436,
                    44,
                    437,
                    41,
                    440,
                    39,
                    442,
                    37,
                    445,
                    33,
                    449,
                    30,
                    452,
                    26,
                    456,
                    21,
                    469,
                    6,
                    77582
                ],
                "size": [
                    480,
                    640
                ]
            },
            "bg_object_segmentation": []
        }, 

Thank you so much!

**Comment by AnnaMariaMeer** [comment]
Hi, 
my annotation file is a RLE format, the segmentation part looks like that: "annotations": [{"id": 1,"image_id": 30,"bbox": [404.0,138.0,75.0,73.0],"area": 5475.0,"iscrowd": 0,"category_id": 1,"segmentation": {"counts": [194104,1,475,1,3,1,475,5,475,5,475,5,475,5,475,3,477,1,462,1,1,3,470,26,451,30,447,33,445,35,8,1,1,3,3,3,425,36,9,12,422,39,7,14,419,40,7,14,418,41,8,13,417,43,7,14,415,45,4,18,412,47,3,17,413,49,1,17,412,50,3,15,411,53,1,15,411,68,411,69,411,69,411,15,4,50,410,15,5,48,412,14,7,47,412,13,8,47,411,13,9,47,411,13,9,47,411,12,10,47,411,12,10,47,411,11,10,47,412,11,10,47,412,10,11,47,412,10,10,50,410,10,10,50,410,11,9,49,411,10,9,50,411,10,9,49,412,11,8,49,412,13,6,48,413,13,6,47,414,13,6,47,414,13,6,46,416,12,3,49,416,13,1,50,416,64,417,63,417,62,419,61,419,61,419,60,421,59,421,59,422,57,424,56,424,56,425,54,427,52,429,51,430,49,432,47,434,45,436,44,437,41,440,39,442,37,445,33,449,30,452,26,456,21,469,6,77582],"size": [480,640]},"bg_object_segmentation": []},

Thank you so much!

**Comment by lkeab** [comment]
you need to deal with the situation where ""bg_object_segmentation" is empty.
