### ISSUE TITLE
About training my dataset

### ISSUE THREAD

**Issue by breezero1994** [lkeab/BCNet#72]
Traceback (most recent call last):
  File "/home/anaconda3/envs/bcnet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/anaconda3/envs/bcnet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/BCNet/detectron2/data/datasets/process_dataset.py", line 584, in <module>
    dicts = load_coco_json(sys.argv[1], sys.argv[2], sys.argv[3])
  File "/home/BCNet/detectron2/data/datasets/process_dataset.py", line 101, in load_coco_json
    meta.thing_classes = thing_classes
  File "/home/BCNet/detectron2/data/catalog.py", line 136, in __setattr__
    "to a different value!\n{} != {}".format(key, self.name, oldval, val)
AssertionError: Attribute 'thing_classes' in the metadata of 'coco_2017_train' cannot be set to a different value!
['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush'] != ['KU', 'PH']

I'm extremely interested in your article. I tried to change images and json files into the coco type. Then I used your process.py to generate new json file. Then it outputted this problem. As you can see, my 'thing_classes' are two kinds ['KU', 'PH']. I want to know where can I change the 'thing_classes', then I can run the model.

Looking forward to your reply.

**Comment by lkeab** [comment]
Hi, please refer to the issue reply [here](https://github.com/lkeab/BCNet/issues/29)

**Comment by breezero1994** [comment]
I changed the thing_classes to my own dataset(2 kinds of things), I deleted your 80 kinds.

But I got another question as following.
[11/23 14:04:16 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
Traceback (most recent call last):
  File "/home/BCNet/detectron2/engine/train_loop.py", line 131, in train
    self.run_step()
  File "/home/BCNet/detectron2/engine/train_loop.py", line 224, in run_step
    losses.backward()
  File "/home/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/anaconda3/envs/bcnet/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train_net.py", line 161, in <module>
    args=(args,),
  File "/home/BCNet/detectron2/engine/launch.py", line 51, in launch
    main_func(*args)
  File "tools/train_net.py", line 149, in main
    return trainer.train()
  File "/home/BCNet/detectron2/engine/defaults.py", line 373, in train
    super().train(self.start_iter, self.max_iter)
  File "/home/BCNet/detectron2/engine/train_loop.py", line 134, in train
    self.after_train()
  File "/home/BCNet/detectron2/engine/train_loop.py", line 142, in after_train
    h.after_train()
  File "/home/BCNet/detectron2/engine/hooks.py", line 353, in after_train
    self._do_eval()
  File "/home/BCNet/detectron2/engine/hooks.py", line 321, in _do_eval
    results = self._func()
  File "/home/BCNet/detectron2/engine/defaults.py", line 324, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/home/BCNet/detectron2/engine/defaults.py", line 485, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/home/BCNet/detectron2/evaluation/evaluator.py", line 158, in inference_on_dataset
    results = evaluator.evaluate()
  File "/home/BCNet/detectron2/evaluation/coco_evaluation.py", line 146, in evaluate
    self._eval_predictions(set(self._tasks), predictions)
  File "/home/BCNet/detectron2/evaluation/coco_evaluation.py", line 169, in _eval_predictions
    category_id
AssertionError: A prediction has category_id=45, which is not available in the dataset.
I don't have the number of the category_id over 2 in my json file. But now I got this mistake.
Sorry to bother u again, looking forward to your reply.

**Comment by breezero1994** [comment]
Hi, I've solved this problem. I opened all files in your project, then I changed all the '80' to '2'.  Another problem occurred, but I found the answer in one issue.  Now the model is running, thanks for your open source code.

**Comment by breezero1994** [comment]
![24](https://user-images.githubusercontent.com/43124483/143528376-90a7fd2b-41b7-46ff-8dc8-7451011a6aaf.jpg)
This one is the input of the model, next one is the output of the net.You can find the effect of model is not good. I found Yolact can do it better. 
![24](https://user-images.githubusercontent.com/43124483/143528507-f14aba11-4731-4761-bc38-ef7cefe89807.jpg)
Here I'm going to introduce what I did. I need to find the fibers in the image. But I only have the small images and corresponding annotations. But I need the model to find the fibers in the big images. I tried your model with small images and their annotations. I validated in big images and got a not good result. Can you give me some advices to adjust the model to improve the result? Thanks a lot.

**Comment by lkeab** [comment]
What's the training epochs for your dataset? What are the number of training images and input image sizes? For improving performance, these are all important. Also, I think data augmentation, such as rotation, will be beneficial in your project.

**Comment by breezero1994** [comment]
My training dataset contains 993 images. The shape of input images is 768x576x3. The max_iter is 90000 and the batch_size is 2.
The test image is 3840x2160. It took me about 6 hours for training.

**Comment by chakri-muthyala** [comment]
> Hi, I've solved this problem. I opened all files in your project, then I changed all the '80' to '2'. Another problem occurred, but I found the answer in one issue. Now the model is running, thanks for your open source code.

@breezero1994 In which files did you change num_classes? I changed it in FCOS detector buy got tensor shape error. You help would be really helpful.

**Comment by trugle** [comment]
> Traceback (most recent call last): File "/home/anaconda3/envs/bcnet/lib/python3.7/runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "/home/anaconda3/envs/bcnet/lib/python3.7/runpy.py", line 85, in _run_code exec(code, run_globals) File "/home/BCNet/detectron2/data/datasets/process_dataset.py", line 584, in dicts = load_coco_json(sys.argv[1], sys.argv[2], sys.argv[3]) File "/home/BCNet/detectron2/data/datasets/process_dataset.py", line 101, in load_coco_json meta.thing_classes = thing_classes File "/home/BCNet/detectron2/data/catalog.py", line 136, in **setattr** "to a different value!\n{} != {}".format(key, self.name, oldval, val) AssertionError: Attribute 'thing_classes' in the metadata of 'coco_2017_train' cannot be set to a different value! ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush'] != ['KU', 'PH']
> 
> I'm extremely interested in your article. I tried to change images and json files into the coco type. Then I used your process.py to generate new json file. Then it outputted this problem. As you can see, my 'thing_classes' are two kinds ['KU', 'PH']. I want to know where can I change the 'thing_classes', then I can run the model.
> 
> Looking forward to your reply.

Unfortunately,I have the same problem,and I want to know how you solved it.
Looking forward to your reply.

**Comment by kieran0625** [comment]
/detectron2-master/detectron2/data/datasets/builtin_meta.py line 194
    #assert len(thing_ids) == 80, len(thing_ids)
    assert len(thing_ids) == 2, len(thing_ids)
