### ISSUE TITLE
About training strategy

### ISSUE THREAD

**Issue by ymy-k** [lkeab/BCNet#75]
Hi! Thanks for your job! Here I have a question about the training strategy. About the training part in your paper, "we filter out part of the non-occluded ROI proposals to keep occlusion cases taking up 50% for balance sampling." I wonder where the filtering operation lies in the code? Thanks

**Comment by lkeab** [comment]
Hi，please check the implementation details from [L126 to L154](https://github.com/lkeab/BCNet/blob/main/detectron2/modeling/roi_heads/mask_head.py#L126)

**Comment by ymy-k** [comment]
Thanks!

**Comment by ymy-k** [comment]
Did you use rotation data augmentation during training

**Comment by ymy-k** [comment]
By the way, did you use rotation augmentation method during training?

**Comment by lkeab** [comment]
no
