### ISSUE TITLE
Meaning of variable

### ISSUE THREAD

**Issue by cp1108** [lkeab/BCNet#76]
mask = predictions['instances'].raw_masks.squeeze(1).data.cpu().numpy() if predictions['instances'].has("raw_masks") else None
        mask_bo = predictions['instances'].pred_masks_bo.squeeze(1).data.cpu().numpy() if predictions['instances'].has("pred_masks_bo") else None
        bound_bo = predictions['instances'].pred_bounds_bo.squeeze(1).data.cpu().numpy() if predictions['instances'].has("pred_bounds_bo") else None
        bound = predictions['instances'].pred_bounds.squeeze(1).data.cpu().numpy() if predictions['instances'].has("pred_bounds") else None

想请问一下您，raw_masks，pred_masks_bo，pred_bounds_bo，pred_bounds这四个变量的含义吗？
还想问一下的是，您好像在知乎专栏的评论里有回复说BCNet和mask-rcnn在训练时间上的差距不大，但我实测了一下相同数据，batch size ，iter，时间上比mask-rcnn慢了一倍有可能是哪些原因导致的呢？我已经将检测器换成了faster-rcnn而不是fcos。谢谢您的工作

**Comment by cp1108** [comment]
还有一个问题是，请问训练集annotation的mask需要是完整的吗？例如物体A是被物体B遮挡的，此时A的mask只有可见部分，会对结果造成影响吗？

**Comment by lkeab** [comment]
1) *_bo are boundary and masks for the occluder, the others are for the occludee
2) The differences between faster rcnn & fcos: With the same hardwares and backbone ResNet-50-FPN, FCOS requires less training hours (6.5h vs. 8.8h) than Faster R-CNN. FCOS also takes 12ms less inference time per image than Faster R-CNN (44ms vs. 56ms).
3) no, object A does not to be complete as long as you only need to predict the visible object masks.

**Comment by cp1108** [comment]
非常感谢您的回答，对于1.2我已经完全理解了。
但是3.如果只预测可见部分的masks，就是最终的预测结果masks只有可见部分吗？那样是如何得到下图这样完整的masks呢？
![image](https://user-images.githubusercontent.com/56954781/147030517-eeefd450-2ab0-4180-bd13-2bd4608ef143.png)
![image](https://user-images.githubusercontent.com/56954781/147030551-b329eb8e-722e-4b37-bdae-3ae72b24753f.png)

**Comment by cp1108** [comment]
其次因为我使用的是custom datasets，大致是将一些objects渲染到随机背景上。通过您的process.sh处理后得到ann.json，但是我可视化“bg_object_segmentation”到原图，发现得到的bg_object_segmentation并不能准确的描述遮挡关系，这会对结果预测遮挡部分的mask造成不好的影响吗？
![000005](https://user-images.githubusercontent.com/56954781/147049055-44b80304-a26d-4a31-873d-ba9b1506415f.jpg)
![000018](https://user-images.githubusercontent.com/56954781/147049086-d0639285-aa6a-4540-9b7e-6b456cdcc9da.jpg)
![000034](https://user-images.githubusercontent.com/56954781/147049092-c5b06bde-a779-4cb5-a1a4-8781c60bcc5c.jpg)
![000037](https://user-images.githubusercontent.com/56954781/147049099-c56fa9ed-5fae-4790-9771-243ed93769d0.jpg)

**Comment by lkeab** [comment]
if 'bg_object_segmentation' are also the visible masks of the other foreground objects in the bounding box, then it will not influence too much.
