### ISSUE TITLE
Amodal Train

### ISSUE THREAD

**Issue by 74284853** [lkeab/BCNet#78]
Following your footsteps, I found in the official README.md contains only the training methods on the coco2017 dataset. I am eager to know how to train the network in Amodal's annotation. Besides, I have a doubt here, in the paper the BCNet decomposes the objects in the picture into **Occluder** and **Occludee** objects. In the data set except Amodal, how to determine which object is **Occluder** or  **Occludee**??

**Comment by lkeab** [comment]
Hi, you could use the [script](https://github.com/lkeab/BCNet#reference-script-for-producing-bilayer-mask-annotation) here to convert the official amodal coco dataset or KINS dataset annotation into bilayer annotation. For how to identify the occluder and occludee, please read the discussion [here](https://github.com/lkeab/BCNet/issues/11).
