### ISSUE TITLE
final mask

### ISSUE THREAD

**Issue by cp1108** [lkeab/BCNet#79]
The final mask is output by the second layer GCN, but as the example in your paper, the horse mask predicted by the second layer GCN is incomplete.  According to the description in your paper, was the contour overlap predicted by GCN of the first layer and GCN of the second layer calculated as the occludee area?  Then, the final mask is to add the mask of the second  GCN to the overlapping part as a post-processing to get the final mask?  If so, where is the post-processing in the code?  Or did I misunderstand?  Thank you

最终的mask是由第二层GCN输出的，但如您论文中的实例，第二层GCN预测的马的mask是不完整的。按您论文中的描述，是通过计算第一层GCN和第二层GCN预测的contour重叠部分作为被遮挡的区域？那么的话，最终的mask是将第二层GCN的mask加上重叠部分，作为一个后处理得到最终的mask吗？如何是的话，后处理在代码中的哪一部分呢？还是我的理解有误？谢谢您
![image](https://user-images.githubusercontent.com/56954781/149355076-8008b97e-6a3a-4931-8650-4cb792dfa2c7.png)

**Comment by cp1108** [comment]
![image](https://user-images.githubusercontent.com/56954781/149364041-2c1ea1f4-453f-4d8e-806c-10f7c42330a3.png)

**Comment by lkeab** [comment]
Hi, it depends on two cases. Amodal and modal, what this means is that in amodal prediction, there will be overlapping between the predicted occluder and occludee objects. But in modal prediction, we only detect the visible parts for both the occluder and occludee. Please see more discussion [here](https://github.com/lkeab/BCNet/issues/28).
