### ISSUE TITLE
Annotations are not available for evaluation.

### ISSUE THREAD

**Issue by Solidays-Hung** [lkeab/BCNet#80]
When I run "CUDA_VISIBLE_DEVICES=0,1 python3 tools/train_net.py --num-gpus 2 --config-file configs/fcos/fcos_imprv_R_101_FPN.yaml --eval-only MODEL.WEIGHTS ./pretrained_models/model_final_beta.pth 2>&1 | tee log/test_log.txt", I got this error "Annotations are not available for evaluation." and no csv file is saved. Why it happens? Thanks!!!

**Comment by lkeab** [comment]
Have you prepared dataset as mentioned [here](https://github.com/lkeab/BCNet#dataset-preparation)?
