### ISSUE TITLE
How to distinguish the occlusion relationship between objects in the result ？

### ISSUE THREAD

**Issue by JaggerYang-code** [lkeab/BCNet#82]
I have completed the training and got the KINS dataset training results as in the article, but found that the instance masks in the result are unordered, I can't distinguish the occlusion relationship between objects ,like the the order of red, green and blue cars in the image. Faithfully ask you how to distinguish in the code.
![image](https://user-images.githubusercontent.com/83537447/153180625-21174461-c2de-4a01-9fa2-b27448e7da79.png)

**Comment by JaggerYang-code** [comment]
> Hi @JaggerYang-code, Can I ask about the score of AP_det and AP_seg that you have reproduced on KINS?

I used a small dataset with only a portion of the KINS data, and I only identified one class, so unfortunately our results cannot be compared. Here are my results: 
[02/08 10:29:27] d2.evaluation.coco_evaluation INFO: Evaluation results for bbox: 
|   AP   |  AP50  |  AP75  |  APs   |  APm  |  APl  |
|:------:|:------:|:------:|:------:|:-----:|:-----:|
| 75.080 | 91.016 | 88.814 | 78.812 |  nan  |  nan  |
[02/08 10:29:27] d2.evaluation.coco_evaluation INFO: Evaluation results for segm: 
|   AP   |  AP50  |  AP75  |  APs   |  APm  |  APl  |
|:------:|:------:|:------:|:------:|:-----:|:-----:|
| 74.571 | 91.207 | 85.328 | 77.822 |  nan  |  nan  |

**Comment by trqminh** [comment]
I see, thanks for your reply @JaggerYang-code!
