### ISSUE TITLE
Reproduce results on KINS dataset

### ISSUE THREAD

**Issue by trqminh** [lkeab/BCNet#83]
Hi @lkeab,
Thank you for your consideration.
I have reproduced the results on the KINS dataset, the training config I used is this one (https://github.com/lkeab/BCNet/blob/main/configs/fcos/fcos_imprv_R_101_FPN.yaml)

This is my result:
Task: bbox
AP,AP50,AP75,APs,APm,APl
22.1250,36.1991,22.7091,7.1252,29.4600,50.7804
Task: segm
AP,AP50,AP75,APs,APm,APl
19.0872,35.3957,18.6023,5.3862,25.6557,49.1075

I think I find that there is a large gap between my results and the reported results
![image](https://user-images.githubusercontent.com/30286786/153483004-3bea8118-4e8e-4055-b961-deb90fe46a40.png)

I would like to ask if I have done something wrong or is there any specific config for the KINS dataset. Thank you.

**Comment by lkeab** [comment]
Training KINS should have difference settings compared to COCO, including lr, iters, lr reduce steps. I followed the same setting [here](https://github.com/qqlu/Amodal-Instance-Segmentation-through-KINS-Dataset/tree/master/Reference%20Code/configs). Also, the results are not that stable due to its small size.

**Comment by trqminh** [comment]
Great, thank for you advice @lkeab

**Comment by trqminh** [comment]
However, do you have your trained model that I can use for doing the evaluation on KINS? Thanks a lot!

**Comment by lkeab** [comment]
Sorry, I didn't preserve that model due to change of work place.

**Comment by usherbob** [comment]
> https://github.com/lkeab/BCNet/blob/main/configs/fcos/fcos_imprv_R_101_FPN.yaml

Hi trqminh, 

Did you reproduce results on KINS?

**Comment by trqminh** [comment]
@usherbob 
yes, I reproduced the kins results of bcnet. however, you need to run with mask rcnn instead of fcos to get the reported performance.

**Comment by trqminh** [comment]
@zhangyufeng1998 
I am a bit occupied now but I'll organize the code and let u know as soon as I can
