### ISSUE TITLE
Too many occlusions detected on custom dataset

### ISSUE THREAD

**Issue by Shadercloud** [lkeab/BCNet#84]
I've been training on a custom dataset using the `fcos_imprv_R_50_FPN.yaml` config and after 28,000 iterations total_loss appears to have stabilized, so I think it's enough to get a fair result.

But I'm getting way more occluded items detected than actually exists.  Note that the dataset includes about 1600 `player` annotations (which is class "0" in the images)

## Original Image: 
<a href="https://ibb.co/jv4fKSG"><img src="https://i.ibb.co/pvXwDSZ/screenshot-20220112-105304.png" alt="screenshot-20220112-105304" border="0"></a>

## BCNet `R_50_FPN` after 28,000 iterations:
<a href="https://ibb.co/6HV1TjF"><img src="https://i.ibb.co/8rTdf19/COCO-detections-screenshot-11-02-2022.png" alt="COCO-detections-screenshot-11-02-2022" border="0"></a>

## Detectron2 using `mask_rcnn_R_50_FPN_3x.yaml` after 5,000 iterations
<a href="https://ibb.co/VVH0pgK"><img src="https://i.ibb.co/7vgxNn9/COCO-detections-screenshot-11-02-2022-2.png" alt="COCO-detections-screenshot-11-02-2022-2" border="0"></a>

## Detectron2 using `mask_rcnn_X_101_32x8d_FPN_3x.yaml` after 25,000 iterations
<a href="https://ibb.co/dKs1ZsP"><img src="https://i.ibb.co/Qm7z07P/COCO-detections-screenshot-11-02-2022-3.png" alt="COCO-detections-screenshot-11-02-2022-3" border="0"></a>

As you can see BCNet is detecting way more instances of overlapping players; whereas both other models got everything almost right, except for the group of 3 players.  How can I solve this?

**Comment by lkeab** [comment]
1. You could filter out the low-score detections such as 3.38% and 3.75%. Only showing the detections with larger scores.
2. Have you made the nms operations?
3. This seems more a bounding box detection problem instead of object segmentation. Maybe you could use the mask head design of BCNet and combine it with the Faster R-CNN detector (replace the maskhead file in original detectron2).

**Comment by lkeab** [comment]
2. NMS means non-maximum suppression. You could do more search on it.
3. One object bounding box corresponds to one instance (the occluded object) mask inside it. The statement " if i give BCnet bounding box that contains 3 players, it's still going to return me like 5 or 6 masks." is wrong. The default object detector in detectron2 is faster r-cnn in our provided model 'fcos' is used to detect objects.
4. The class imbalance will influence the object detection training accuracy.
