### ISSUE TITLE
COCOA training

### ISSUE THREAD

**Issue by trqminh** [lkeab/BCNet#87]
Hi @lkeab,

Thank you for your consideration.
It occurs to me that the COCOA training annotation does not contain the categories. Therefore, I think I cannot train it with BCNet or detectron 2 in general (Correct me if I am wrong.)
However, it has a corresponding name for each region. How did you deal with this?

**Comment by lkeab** [comment]
in the config file, you can set the training in a class agnostic way. Or you treat all with the same foreground class, only one class, the remaining are backgrounds.
