### ISSUE TITLE
training about my dataset

### ISSUE THREAD

**Issue by kenny30725** [lkeab/BCNet#89]
Thanks for your open source.  When i training my dataset, I have some problem.
The error is KeyError: 'bg_object_segmentation', then  I Comment out the line about the bg_object_segmentation.
After done the above said, the error is  "AttributeError: Cannot find field 'gt_bo_masks' in the given Instances!"
How can i fix it ? Should I add the "bg_object_segmentation" in json file?

**Comment by lkeab** [comment]
you could refer to the provided script [here](https://github.com/lkeab/BCNet#reference-script-for-producing-bilayer-mask-annotation) for producing bilayer annotations, which contain the the field 'gt_bo_masks'.

**Comment by kenny30725** [comment]
Thanks,I have found the process.sh and run it .
But it also have the error about KeyError: 'bg_object_segmentation'

**Comment by kenny30725** [comment]
And when I use original pascal voc 2012 to training. It have the same error about :
AttributeError: 'Instances' object has no attribute 'pred_boxes'  &&  AttributeError: 'Instances' object has no attribute 'gt_boxes'
