### ISSUE TITLE
Where is the new dataset?

### ISSUE THREAD

**Issue by Len-Li** [lkeab/BCNet#9]
Hi, thanks for your awesome work. 

After reading your paper, I noticed that there should be a new synthetic occlusion dataset. Where can I found it? And could you make your supplementary available on arixv?

Thanks .

**Comment by lkeab** [comment]
Hi, thanks for watching our work! The supplementary file will be released on CVF pages in June, which has more content description regarding how to generate/use the synthetic dataset (which is now internally used by the company and need permission for release). When comparing with other methods on the coco or kins etc. leaderboard, we don't use external training data for fair comparison.

**Comment by lkeab** [comment]
[Deep_Occlusion_Aware_Instance_Segmentation_with_Overlapping_BiLayers__Supplemental_material_.pdf](https://github.com/lkeab/BCNet/files/6445602/Deep_Occlusion_Aware_Instance_Segmentation_with_Overlapping_BiLayers__Supplemental_material_.pdf)

Here is the supp file for you to preview.
