### ISSUE TITLE
Code for generating synthetic data.

### ISSUE THREAD

**Issue by usherbob** [lkeab/BCNet#90]
Hi Lei Ke,

I read your description about generating synthetic data in your supplemental. The process of occlusion is heuristic and I wonder if you may share your code for this process.

Best regards,
Jiahua

**Comment by lkeab** [comment]
sorry I changed a new working environment last year; this part is not reserved but it may be easy to implement by randomly permutating the different instance mask locations and then computing the overlapping IoU.
