### ISSUE TITLE
Question about training 

### ISSUE THREAD

**Issue by kenny30725** [lkeab/BCNet#91]
Thanks for the previous response,I have found the process.sh and run it .
But it also have the error about :
KeyError: 'bg_object_segmentation' & AttributeError: 'Instances' object has no attribute 'pred_boxes'.

And when I use original pascal voc 2012 to training. It have the same error about :
AttributeError: 'Instances' object has no attribute 'pred_boxes' && AttributeError: 'Instances' object has no attribute 'gt_boxes'.

**Comment by comingsoon1204** [comment]
how？I have the same question
