### ISSUE TITLE
Run on the new version of detectron2

### ISSUE THREAD

**Issue by sssjing** [lkeab/BCNet#95]
Hi lkeab, I'm still learning
Thank you again for your work!
When I cloned the project files on another windows system, the code didn't work as expected when I used the familiar detectron2 command. However, the detectron2 I use is well compatible. 
I would like to know how I can migrate all your code to the new version of detectron2.

**Comment by lkeab** [comment]
Hi, please refer to the discussion [here](https://github.com/lkeab/BCNet/issues/81).
